# Generated by Django 5.0.3 on 2024-03-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSystem', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
