# Generated by Django 5.0.3 on 2024-03-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSystem', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bool_model',
            name='true_false',
        ),
        migrations.AddField(
            model_name='bool_model',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], default='not_paid', max_length=10),
        ),
    ]
