# Generated by Django 5.0.3 on 2024-03-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSystem', '0006_alter_bool_model_payment_status_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_img',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
