# Generated by Django 5.0.3 on 2024-03-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSystem', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
