# Generated by Django 5.0.3 on 2024-03-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthSystem', '0009_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
